### ISSUE TITLE
Urls with query params fail

### ISSUE THREAD

**Issue by chriswhite199** [akamai-open/edgegrid-curl#11] opened 2016-01-28 21:54 UTC
```
./egcurl -sk 'https://xxx.luna.akamaiapis.net/network-list/v1/network_lists?listType=IP' --eg-verbose
DEBUG: String-to-sign: GET     https   xxx.luna.akamaiapis.net      /network-list/v1/network_lists                  EG1-HMAC-SHA256 ....
DEBUG: curl Arguments: ['curl', '-H', 'Authorization: EG1-HMAC-SHA256 ...', '-s', '-k', 'https://xxx.luna.akamaiapis.net/network-list/v1/network_lists?listType=IP', '-H', 'Expect:']
{
  "type": "https://problems.luna.akamaiapis.net/-/pep-authn/deny",
  "title": "Not authorized",
  "status": 401,
  "detail": "The signature does not match",
  "instance": "https://xxx.luna.akamaiapis.net/network-list/v1/network_lists?listType=IP",
  "method": "GET",
}
```

As you can see the String to sign doesn't include the query portion of the URL, as required in the spec

**Comment by lukaszczerpak** [comment] 2016-03-30 11:56
It seems to be working fine right now (fixed by https://github.com/akamai-open/edgegrid-curl/commit/173aa22e0b4b4697b51a5a480d5976762d7e9932)

**Comment by elreydetodo** [comment] 2016-11-07 21:52
Marking as resolved since I cannot reproduce and it's been observed to have been fixed.

**Closed by elreydetodo** 2016-11-07 21:52 UTC
